### PR TITLE
upgrade to node 18.

### PR DESCRIPTION
**Pull request by stopfstedt**
it's the current stable, let's use it.

### CODE REVIEW

**Comment by jrjohnson** [comment]
Bump this too please https://github.com/ilios/lti-server/blob/master/serverless.yml#L23

**Comment by stopfstedt** [comment]
> Bump this too please https://github.com/ilios/lti-server/blob/master/serverless.yml#L23

handled. :heavy_check_mark:

**Review by jrjohnson — APPROVED** [review]

**Review by jrjohnson — CHANGES_REQUESTED** [review]
Forgot about all the v16 stuff in https://github.com/ilios/lti-server/tree/master/.github/workflows also needs updating.

**Comment by stopfstedt** [comment]
> Forgot about all the v16 stuff in https://github.com/ilios/lti-server/tree/master/.github/workflows also needs updating.

thanks, handled :heavy_check_mark:

**Pull request merged**
